config/routes.rb
Rails.application.routes.draw do
  resources :memos do
    post :import, on: :collection
  end
  root to: 'memos#index'
  resources :users, only: [:new, :create]
  
  get '/login', to: 'sessions#new'
  post '/login',  to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  # get 'memos/index'
  # get 'memos/show'
  # get 'memos/new'
  # get 'memos/edit'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/memo.rb
class Memo < ApplicationRecord
    belongs_to :user

    # CSV出力する項目の順番を指定するための配列を作成するメソッド
    def self.csv_attributes
        [:title, :memo_text, :created_at, :updated_at, :user_id]
    end

    def self.generate_csv
        CSV.generate(headers: true) do | csv |
            #self.csv_attributesで作成した配列の順番でcsvのヘッダー（項目名を作成）
            csv << csv_attributes
            # memosテーブルのレコードを一行ずつファイルに出力している。
            all.each do | memo |
                csv << csv_attributes.map{ |attr| memo.send(attr) }
            end
        end
    end

    def self.import(file)
        # ファイルを一行ずつ読み込むためのループ、一行目はヘッダーとしての行なので読み込まないように指定
        CSV.foreach(file.path, headers: true) do |row|
            # memo = new という省略記法もできる。
            memo = self.new
            #ヘッダーの項目に対応する値を取得している
            memo.attributes = row.to_hash
            memo.save!
        end
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :memos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    #ヘルパーメソッドを定義することで全てのビューから使える。
    helper_method :current_user 

    private

    def current_user
        # session変数にログインユーザーのIDが存在して、なおかつ@current_userの中身が nil の場合。
        # session変数のユーザーIDと一致するユーザーの情報を@current_userの中に格納する。
        # ||=はnilガード、左辺の変数が空の時だけ値を代入して、すでに値があれば何もしない。
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id] #後置if session[:id]の中身が存在するかどうかを判定。
    end
end

app/controllers/memos_controller.rb
class MemosController < ApplicationController
  before_action :login_required

  def index
    # @memos = Memo.all
    @memos = current_user.memos.all.page(params[:page]).per(10) #こう (10件区切りで表示するように指定)

    #リクエストされた形式によって画面（html）を表示する場合とCSVファイルを出力する場合を分けている。
    respond_to do |format|
      format.html
      #CSV形式で出力された場合のファイル名を指定
      format.csv { send_data @memos.generate_csv, filename: "memos-#{Time.zone.now.strftime('%Y%m%d%S')}.csv" }
    end
  end

  def show
    @memos = current_user.memos.all.page(params[:page]).per(10)
  end

  def new
    @memo = Memo.new
  end

  def create
    @memo = current_user.memos.new(memo_params)
    if @memo.save
      redirect_to root_path, notice: "メモ「#{@memo.title}」を登録しました。"
    else
      render :new
    end
  end

  def edit
    @memo = Memo.find(params[:id])
  end

  def update
    memo = Memo.find(params[:id])
    memo.update!(memo_params)
    redirect_to root_path, notice: "メモ「#{memo.title}」を編集しました。"
  end

  def destroy
    memo = Memo.find(params[:id])
    memo.destroy
    redirect_to root_path, notice: "メモ「#{memo.title}」を削除しました。"
  end

  def import
    current_user.memos.import(params[:file])
    redirect_to root_path, notice: "CSVインポートを行いました。"
  end

  private
  def memo_params
    params.require(:memo).permit(:title, :memo_text)
  end

  def login_required
    redirect_to login_path unless current_user
   end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    # 入力されたメールアドレスに該当するユーザーを取得する。
    user = User.find_by(email: session_params[:email])

    # authenticateメソッドは、入力されたパスワードをハッシュ化し。
    # usersテーブルに保存されているパスワード（既にハッシュ化されているもの）を比較して一致するかどうかを判定する。
    # &.は「ぼっちメソッド」とも呼ばれ。直前に書いているオブジェクトが空(nil)の場合を許容する（エラーを握り潰す)※nilを許容できないものには使用しないこと。
    if user&.authenticate(session_params[:password])
      # セッション変数にログイン成功したユーザーのIDを格納している。セッションが切れるまで保持され続ける。
      login(user)
      redirect_to root_path, notice: 'ログインしました'
    else
      render :new
    end
  end

  def destroy
    session.delete(:user_id)
    redirect_to root_path, notice: 'ログアウトしました'
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      login(@user)
      redirect_to root_path, notice: "ユーザーを登録しました。"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :email, :password, :password_cofirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/memos_helper.rb
module MemosHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MemoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%# メッセージが存在すればメッセージを表示する。 %>
    <% if flash.notice.present? %>
      <div class="c-alert c-alert--success">
        <%= flash.notice %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/memos/edit.html.erb
<h1 class="c-page_title">メモの編集</h1>

<%= link_to '一覧', memos_path, class: 'c-link'%>

<%= form_with model: @memo, local: true, html: { class: 'c-form' } do |f| %>
    <%= f.label :title, class: 'c-form__label' %>
    <%= f.text_field :title, class: 'c-form__text' %>

    <%= f.label :memo_text, class: 'c-form__label' %>
    <%= f.text_area :memo_text, class: 'c-form__textarea' %>

    <%= f.submit nil, class: 'c-btn c-button__success' %>
<% end %>

app/views/memos/index.html.erb
<div class="test">
    <li>
        <ul></ul>
        <ul></ul>
        <ul></ul>
        <ul></ul>
        <ul></ul>
    </li>
</div>



<header>
    <%= link_to 'ユーザー登録', new_user_path %>
    <%= link_to 'ログイン', login_path %>
    <%= link_to 'ログアウト', logout_path, method: :delete, class: 'c-header__nav' %>
    <% if current_user && current_user.email %>
        <span class="c-header__nav">
            <%= t 'memos.welcom_user', :user_email => current_user.email %>
        </span>
    <% end %>
</header>

<h1 class="c-page_title"><%= t 'memos.title' %></h1>

<%= link_to 'メモの登録', new_memo_path, class: 'c-btn'%>
<%= link_to 'CSV出力', memos_path(format: :csv), class: 'c-btn'%>
<%= form_tag import_memos_path, multipart: true, html: { class: 'c-form' } do %>
    <%= file_field_tag :file %>
    <%= submit_tag "インポート", class: 'c-btn c-button__success' %>
<% end %>

<table class="c-table">
    <tbody class="c-table__body">

        <%# @memosにはmemosテーブルの情報が[{id: 1, title: "テストタイトル", memo_text: "買い物"}, {id: 2, title: "テスト2", memo_text: "掃除"}]のような配列の形式で
        データが入っている。繰り返し処理をするためのeach文を使うことでレコードを一つ一つ変数「memo」の中に格納している。
        配列の中身が全て出力されるまで繰り返されるのでその回数文のメモのタイトルと作成日時が表形式で出力される %>

        <% @memos.each do |memo| %>
            <tr class="c-table__tr">
                <td class="c-table__td">
                    <%= link_to memo.title, memo, class: 'c-link'%>
                </td>
                <td class="c-table__td">
                    <%= memo.created_at %>
                </td>

                <td class="c-table__td">
                    <%= link_to '編集', edit_memo_path(memo), class: 'c-link'%>
                </td>

                <td class="c-table__td">
                    <!-- link_toでは何も指定しなければHTTPメソッドにはGETが指定される。削除のためにはDELETEに送る必要があるので「method: :delete」を指定する。 -->
　　　　　　　　　　　　<!-- javascriptのalertの機能を使用して確認ダイアログも表示している。 -->
                    <%= link_to '削除', memo_path(memo), method: :delete, data: { confirm: "日記「#{memo.title}」を削除します。よろしいですか？"}, class: 'c-btn c-btn--danger' %>
                </td>
            </tr>
        <% end %>
    </tbody>
</table>
<div>
    <%= paginate @memos %>
</div>

app/views/memos/new.html.erb
<h1 class="c-page_title">メモ登録</h1>

<%= link_to '一覧', memos_path, class: 'c-link'%>

<%= form_with model: @memo, local: true, html: { class: 'c-form' } do |f| %>
    <%= f.label :title, class: 'c-form__label' %>
    <%= f.text_field :title, class: 'c-form__text' %>
　　　<%# :title ではなく "title"のような文字列指定をすることもできるが、シンボルを使用したほうがメモリの消費量が少なくて済む。 %>

    <%# <label for="" class="c-form__label">Title</label>
    <input type="text" class="c-form__text" name="title"> のようなHTMLを作成している。%>


    <%= f.label :memo_text, class: 'c-form__label' %>
    <%= f.text_area :memo_text, class: 'c-form__textarea' %>
    <%= f.submit nil, class: 'c-btn c-button__success' %>
<% end %>

app/views/memos/show.html.erb
<h1 class="c-page_title">
    <%= @memo.title %>
</h1>
<p class="c-text_section">
    <%= simple_format(@memo.memo_text) %>
</p>

app/views/users/new.html.erb
<h1 class="c-page_title">ユーザー登録</h1>

<%= form_with model: @user, local: true, html: { class: 'c-form' } do |f| %>
    <%= f.label :email, class: 'c-form__label' %>
    <%= f.text_field :email, class: 'c-form__text' %>

    <%= f.label :password, class: 'c-form__label' %>
    <%= f.password_field :password, class: 'c-form__text' %>

    <%= f.label :password_confirmation, class: 'c-form__label' %>
    <%= f.password_field :password_confirmation, class: 'c-form__text' %>

    <%= f.submit nil, class: 'c-btn c-button__success' %>
<% end %>